Codebreaker Gem
DaniilYusha/codebreaker pull request #1
Opened 2020-07-14 21:46 UTC by DaniilYusha

2020-07-16 12:21 UTC, Dimasfullxq requested changes

2020-07-16 12:21 UTC, Dimasfullxq commented on lib/codebreaker/entities/difficulty.rb
> +    LIST = { easy: { attempts: 15, hints: 2 },
Nit: It would be cool to rename in DIFFICULTY_LIST to concretise role of variable.

2020-07-16 12:21 UTC, Dimasfullxq commented on lib/codebreaker/entities/game.rb
> +      @errors = []
Am I right, you keep all errors in ```@errors``` and then in console you will raise/rescue them?

2020-07-16 12:32 UTC, DaniilYusha commented on lib/codebreaker/entities/game.rb
> +      @errors = []
Yeap, I heard this idea from Denis at a lecture and thought it was a good option for implementing validations
In console just use something like:
`
raise @error unless game.valid?
`

2020-07-16 12:33 UTC, DaniilYusha commented on lib/codebreaker/entities/difficulty.rb
> +    LIST = { easy: { attempts: 15, hints: 2 },
Okay, thanks :)

2020-07-16 12:38 UTC, Dimasfullxq commented on lib/codebreaker/entities/game.rb
> +      @errors = []
Ok, got it. 🚀

2020-07-16 13:40 UTC, katiakub approved these changes
Everything is awesome!

2020-07-16 13:40 UTC, katiakub commented on lib/codebreaker/errors/expected_user_instance_error.rb
> +  # ExpectedUserInstanceError class called when object is not an instance of User class
NIT: delete the comments, pls

2020-07-16 18:44 UTC, exposwingie approved these changes
looks good 👍

2020-07-16 20:23 UTC, DaniilYusha commented on lib/codebreaker/errors/expected_user_instance_error.rb
> +  # ExpectedUserInstanceError class called when object is not an instance of User class
Rubocop requires comments before class and modules and at the Library task menor didn't allow to disable Style/Documentation cop :( So, I want to ask our mentor about that
As for the default comments in other files, I agree with you, I will remove them) Thanks)

2020-07-17 13:49 UTC, Dimasfullxq approved these changes
Well done!

2020-07-22 14:42 UTC, Svatok commented on lib/codebreaker/entities/guess_checker.rb
> +      matches
please rename to `compose_result`

2020-07-22 15:13 UTC, DaniilYusha commented on lib/codebreaker/entities/guess_checker.rb
> +      matches
Done

2020-07-27 15:26 UTC, Svatok approved these changes

2021-02-10 00:48 UTC, merged